.TH TMATRIX "10" "February 2019" "tmatrix 0.1" "User Commands"
.SH NAME
tmatrix - run matrix
.SH SYNOPSIS
.B tmatrix
[\fI\,OPTION\/\fR]...
.SH DESCRIPTION
Draws a colorful matrix of widecharsymbols.

Options:
.TP
.B Colors:
.TP
\fB\-a\fR
Aqua
.TP
\fB\-b\fR
BLUE
.TP
\fB\-c\fR
CYAN
.TP
\fB\-p\fR
PINK
.TP
\fB\-w\fR
WHITE
.TP
\fB\-r\fR
RED
.TP
\fB\-y\fR
YELLOW
.TP
.B Program options:
.TP
\fB\-chance [number]\fR
Set random symbol chance spawn (1/chance)
.TP
\fB\-speed [number]\fR
Set speed of tmatrix (ms)
.TP
\fB\-length [number]\fR
Set falling line length
.TP
.B Other:
.TP
\fB\-help\fR
Show help menu
.TP
\fB\-v\fR
Version
.SH AUTHORS
Authored by Vladislav Dalechyn, 2018.
